name: Build Image

on: push

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Cross build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/ppc64le
          context: .
          push: false
          load: true
          tags: registry.ppc64le/app:latest

      - name: Inspect docker image
        run: |
          docker image inspect registry.ppc64le/app:latest | grep Arch
          
